// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gtpo.proto

#ifndef PROTOBUF_gtpo_2eproto__INCLUDED
#define PROTOBUF_gtpo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/any.pb.h>
// @@protoc_insertion_point(includes)

namespace gtpo {
namespace pb {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_gtpo_2eproto();
void protobuf_AssignDesc_gtpo_2eproto();
void protobuf_ShutdownFile_gtpo_2eproto();

class Edge;
class Graph;
class Group;
class Node;
class Void;

// ===================================================================

class Node : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gtpo.pb.Node) */ {
 public:
  Node();
  virtual ~Node();

  Node(const Node& from);

  inline Node& operator=(const Node& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Node& default_instance();

  void Swap(Node* other);

  // implements Message ----------------------------------------------

  inline Node* New() const { return New(NULL); }

  Node* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Node& from);
  void MergeFrom(const Node& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Node* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 node_id = 1;
  void clear_node_id();
  static const int kNodeIdFieldNumber = 1;
  ::google::protobuf::int32 node_id() const;
  void set_node_id(::google::protobuf::int32 value);

  // optional string label = 2;
  void clear_label();
  static const int kLabelFieldNumber = 2;
  const ::std::string& label() const;
  void set_label(const ::std::string& value);
  void set_label(const char* value);
  void set_label(const char* value, size_t size);
  ::std::string* mutable_label();
  ::std::string* release_label();
  void set_allocated_label(::std::string* label);

  // optional double x = 3;
  void clear_x();
  static const int kXFieldNumber = 3;
  double x() const;
  void set_x(double value);

  // optional double y = 4;
  void clear_y();
  static const int kYFieldNumber = 4;
  double y() const;
  void set_y(double value);

  // optional double z = 5;
  void clear_z();
  static const int kZFieldNumber = 5;
  double z() const;
  void set_z(double value);

  // optional double width = 6;
  void clear_width();
  static const int kWidthFieldNumber = 6;
  double width() const;
  void set_width(double value);

  // optional double height = 7;
  void clear_height();
  static const int kHeightFieldNumber = 7;
  double height() const;
  void set_height(double value);

  // optional int32 group_id = 8;
  void clear_group_id();
  static const int kGroupIdFieldNumber = 8;
  ::google::protobuf::int32 group_id() const;
  void set_group_id(::google::protobuf::int32 value);

  // optional .google.protobuf.Any user1 = 42;
  bool has_user1() const;
  void clear_user1();
  static const int kUser1FieldNumber = 42;
  const ::google::protobuf::Any& user1() const;
  ::google::protobuf::Any* mutable_user1();
  ::google::protobuf::Any* release_user1();
  void set_allocated_user1(::google::protobuf::Any* user1);

  // @@protoc_insertion_point(class_scope:gtpo.pb.Node)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr label_;
  double x_;
  double y_;
  ::google::protobuf::int32 node_id_;
  ::google::protobuf::int32 group_id_;
  double z_;
  double width_;
  double height_;
  ::google::protobuf::Any* user1_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_gtpo_2eproto();
  friend void protobuf_AssignDesc_gtpo_2eproto();
  friend void protobuf_ShutdownFile_gtpo_2eproto();

  void InitAsDefaultInstance();
  static Node* default_instance_;
};
// -------------------------------------------------------------------

class Edge : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gtpo.pb.Edge) */ {
 public:
  Edge();
  virtual ~Edge();

  Edge(const Edge& from);

  inline Edge& operator=(const Edge& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Edge& default_instance();

  void Swap(Edge* other);

  // implements Message ----------------------------------------------

  inline Edge* New() const { return New(NULL); }

  Edge* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Edge& from);
  void MergeFrom(const Edge& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Edge* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 edge_id = 1;
  void clear_edge_id();
  static const int kEdgeIdFieldNumber = 1;
  ::google::protobuf::int32 edge_id() const;
  void set_edge_id(::google::protobuf::int32 value);

  // optional int32 src_node_id = 2;
  void clear_src_node_id();
  static const int kSrcNodeIdFieldNumber = 2;
  ::google::protobuf::int32 src_node_id() const;
  void set_src_node_id(::google::protobuf::int32 value);

  // optional int32 dst_node_id = 3;
  void clear_dst_node_id();
  static const int kDstNodeIdFieldNumber = 3;
  ::google::protobuf::int32 dst_node_id() const;
  void set_dst_node_id(::google::protobuf::int32 value);

  // optional double weight = 4;
  void clear_weight();
  static const int kWeightFieldNumber = 4;
  double weight() const;
  void set_weight(double value);

  // optional double z = 5;
  void clear_z();
  static const int kZFieldNumber = 5;
  double z() const;
  void set_z(double value);

  // optional .google.protobuf.Any user1 = 42;
  bool has_user1() const;
  void clear_user1();
  static const int kUser1FieldNumber = 42;
  const ::google::protobuf::Any& user1() const;
  ::google::protobuf::Any* mutable_user1();
  ::google::protobuf::Any* release_user1();
  void set_allocated_user1(::google::protobuf::Any* user1);

  // @@protoc_insertion_point(class_scope:gtpo.pb.Edge)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 edge_id_;
  ::google::protobuf::int32 src_node_id_;
  double weight_;
  double z_;
  ::google::protobuf::Any* user1_;
  ::google::protobuf::int32 dst_node_id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_gtpo_2eproto();
  friend void protobuf_AssignDesc_gtpo_2eproto();
  friend void protobuf_ShutdownFile_gtpo_2eproto();

  void InitAsDefaultInstance();
  static Edge* default_instance_;
};
// -------------------------------------------------------------------

class Group : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gtpo.pb.Group) */ {
 public:
  Group();
  virtual ~Group();

  Group(const Group& from);

  inline Group& operator=(const Group& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Group& default_instance();

  void Swap(Group* other);

  // implements Message ----------------------------------------------

  inline Group* New() const { return New(NULL); }

  Group* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Group& from);
  void MergeFrom(const Group& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Group* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 group_id = 1;
  void clear_group_id();
  static const int kGroupIdFieldNumber = 1;
  ::google::protobuf::int32 group_id() const;
  void set_group_id(::google::protobuf::int32 value);

  // optional string label = 2;
  void clear_label();
  static const int kLabelFieldNumber = 2;
  const ::std::string& label() const;
  void set_label(const ::std::string& value);
  void set_label(const char* value);
  void set_label(const char* value, size_t size);
  ::std::string* mutable_label();
  ::std::string* release_label();
  void set_allocated_label(::std::string* label);

  // optional double x = 3;
  void clear_x();
  static const int kXFieldNumber = 3;
  double x() const;
  void set_x(double value);

  // optional double y = 4;
  void clear_y();
  static const int kYFieldNumber = 4;
  double y() const;
  void set_y(double value);

  // optional double z = 5;
  void clear_z();
  static const int kZFieldNumber = 5;
  double z() const;
  void set_z(double value);

  // optional double width = 6;
  void clear_width();
  static const int kWidthFieldNumber = 6;
  double width() const;
  void set_width(double value);

  // optional double height = 7;
  void clear_height();
  static const int kHeightFieldNumber = 7;
  double height() const;
  void set_height(double value);

  // repeated int32 node_ids = 12;
  int node_ids_size() const;
  void clear_node_ids();
  static const int kNodeIdsFieldNumber = 12;
  ::google::protobuf::int32 node_ids(int index) const;
  void set_node_ids(int index, ::google::protobuf::int32 value);
  void add_node_ids(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      node_ids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_node_ids();

  // optional .google.protobuf.Any user1 = 42;
  bool has_user1() const;
  void clear_user1();
  static const int kUser1FieldNumber = 42;
  const ::google::protobuf::Any& user1() const;
  ::google::protobuf::Any* mutable_user1();
  ::google::protobuf::Any* release_user1();
  void set_allocated_user1(::google::protobuf::Any* user1);

  // @@protoc_insertion_point(class_scope:gtpo.pb.Group)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr label_;
  double x_;
  double y_;
  double z_;
  double width_;
  double height_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > node_ids_;
  mutable int _node_ids_cached_byte_size_;
  ::google::protobuf::Any* user1_;
  ::google::protobuf::int32 group_id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_gtpo_2eproto();
  friend void protobuf_AssignDesc_gtpo_2eproto();
  friend void protobuf_ShutdownFile_gtpo_2eproto();

  void InitAsDefaultInstance();
  static Group* default_instance_;
};
// -------------------------------------------------------------------

class Void : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gtpo.pb.Void) */ {
 public:
  Void();
  virtual ~Void();

  Void(const Void& from);

  inline Void& operator=(const Void& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Void& default_instance();

  void Swap(Void* other);

  // implements Message ----------------------------------------------

  inline Void* New() const { return New(NULL); }

  Void* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Void& from);
  void MergeFrom(const Void& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Void* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:gtpo.pb.Void)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_gtpo_2eproto();
  friend void protobuf_AssignDesc_gtpo_2eproto();
  friend void protobuf_ShutdownFile_gtpo_2eproto();

  void InitAsDefaultInstance();
  static Void* default_instance_;
};
// -------------------------------------------------------------------

class Graph : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gtpo.pb.Graph) */ {
 public:
  Graph();
  virtual ~Graph();

  Graph(const Graph& from);

  inline Graph& operator=(const Graph& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Graph& default_instance();

  void Swap(Graph* other);

  // implements Message ----------------------------------------------

  inline Graph* New() const { return New(NULL); }

  Graph* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Graph& from);
  void MergeFrom(const Graph& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Graph* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 node_count = 1;
  void clear_node_count();
  static const int kNodeCountFieldNumber = 1;
  ::google::protobuf::int32 node_count() const;
  void set_node_count(::google::protobuf::int32 value);

  // optional int32 edge_count = 2;
  void clear_edge_count();
  static const int kEdgeCountFieldNumber = 2;
  ::google::protobuf::int32 edge_count() const;
  void set_edge_count(::google::protobuf::int32 value);

  // optional int32 group_count = 3;
  void clear_group_count();
  static const int kGroupCountFieldNumber = 3;
  ::google::protobuf::int32 group_count() const;
  void set_group_count(::google::protobuf::int32 value);

  // repeated .google.protobuf.Any nodes = 12;
  int nodes_size() const;
  void clear_nodes();
  static const int kNodesFieldNumber = 12;
  const ::google::protobuf::Any& nodes(int index) const;
  ::google::protobuf::Any* mutable_nodes(int index);
  ::google::protobuf::Any* add_nodes();
  ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any >*
      mutable_nodes();
  const ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any >&
      nodes() const;

  // repeated .google.protobuf.Any edges = 13;
  int edges_size() const;
  void clear_edges();
  static const int kEdgesFieldNumber = 13;
  const ::google::protobuf::Any& edges(int index) const;
  ::google::protobuf::Any* mutable_edges(int index);
  ::google::protobuf::Any* add_edges();
  ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any >*
      mutable_edges();
  const ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any >&
      edges() const;

  // repeated .google.protobuf.Any groups = 14;
  int groups_size() const;
  void clear_groups();
  static const int kGroupsFieldNumber = 14;
  const ::google::protobuf::Any& groups(int index) const;
  ::google::protobuf::Any* mutable_groups(int index);
  ::google::protobuf::Any* add_groups();
  ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any >*
      mutable_groups();
  const ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any >&
      groups() const;

  // @@protoc_insertion_point(class_scope:gtpo.pb.Graph)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 node_count_;
  ::google::protobuf::int32 edge_count_;
  ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any > nodes_;
  ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any > edges_;
  ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any > groups_;
  ::google::protobuf::int32 group_count_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_gtpo_2eproto();
  friend void protobuf_AssignDesc_gtpo_2eproto();
  friend void protobuf_ShutdownFile_gtpo_2eproto();

  void InitAsDefaultInstance();
  static Graph* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Node

// optional int32 node_id = 1;
inline void Node::clear_node_id() {
  node_id_ = 0;
}
inline ::google::protobuf::int32 Node::node_id() const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Node.node_id)
  return node_id_;
}
inline void Node::set_node_id(::google::protobuf::int32 value) {
  
  node_id_ = value;
  // @@protoc_insertion_point(field_set:gtpo.pb.Node.node_id)
}

// optional string label = 2;
inline void Node::clear_label() {
  label_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Node::label() const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Node.label)
  return label_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Node::set_label(const ::std::string& value) {
  
  label_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gtpo.pb.Node.label)
}
inline void Node::set_label(const char* value) {
  
  label_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gtpo.pb.Node.label)
}
inline void Node::set_label(const char* value, size_t size) {
  
  label_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gtpo.pb.Node.label)
}
inline ::std::string* Node::mutable_label() {
  
  // @@protoc_insertion_point(field_mutable:gtpo.pb.Node.label)
  return label_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Node::release_label() {
  // @@protoc_insertion_point(field_release:gtpo.pb.Node.label)
  
  return label_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Node::set_allocated_label(::std::string* label) {
  if (label != NULL) {
    
  } else {
    
  }
  label_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), label);
  // @@protoc_insertion_point(field_set_allocated:gtpo.pb.Node.label)
}

// optional double x = 3;
inline void Node::clear_x() {
  x_ = 0;
}
inline double Node::x() const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Node.x)
  return x_;
}
inline void Node::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:gtpo.pb.Node.x)
}

// optional double y = 4;
inline void Node::clear_y() {
  y_ = 0;
}
inline double Node::y() const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Node.y)
  return y_;
}
inline void Node::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:gtpo.pb.Node.y)
}

// optional double z = 5;
inline void Node::clear_z() {
  z_ = 0;
}
inline double Node::z() const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Node.z)
  return z_;
}
inline void Node::set_z(double value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:gtpo.pb.Node.z)
}

// optional double width = 6;
inline void Node::clear_width() {
  width_ = 0;
}
inline double Node::width() const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Node.width)
  return width_;
}
inline void Node::set_width(double value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:gtpo.pb.Node.width)
}

// optional double height = 7;
inline void Node::clear_height() {
  height_ = 0;
}
inline double Node::height() const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Node.height)
  return height_;
}
inline void Node::set_height(double value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:gtpo.pb.Node.height)
}

// optional int32 group_id = 8;
inline void Node::clear_group_id() {
  group_id_ = 0;
}
inline ::google::protobuf::int32 Node::group_id() const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Node.group_id)
  return group_id_;
}
inline void Node::set_group_id(::google::protobuf::int32 value) {
  
  group_id_ = value;
  // @@protoc_insertion_point(field_set:gtpo.pb.Node.group_id)
}

// optional .google.protobuf.Any user1 = 42;
inline bool Node::has_user1() const {
  return !_is_default_instance_ && user1_ != NULL;
}
inline void Node::clear_user1() {
  if (GetArenaNoVirtual() == NULL && user1_ != NULL) delete user1_;
  user1_ = NULL;
}
inline const ::google::protobuf::Any& Node::user1() const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Node.user1)
  return user1_ != NULL ? *user1_ : *default_instance_->user1_;
}
inline ::google::protobuf::Any* Node::mutable_user1() {
  
  if (user1_ == NULL) {
    user1_ = new ::google::protobuf::Any;
  }
  // @@protoc_insertion_point(field_mutable:gtpo.pb.Node.user1)
  return user1_;
}
inline ::google::protobuf::Any* Node::release_user1() {
  // @@protoc_insertion_point(field_release:gtpo.pb.Node.user1)
  
  ::google::protobuf::Any* temp = user1_;
  user1_ = NULL;
  return temp;
}
inline void Node::set_allocated_user1(::google::protobuf::Any* user1) {
  delete user1_;
  user1_ = user1;
  if (user1) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:gtpo.pb.Node.user1)
}

// -------------------------------------------------------------------

// Edge

// optional int32 edge_id = 1;
inline void Edge::clear_edge_id() {
  edge_id_ = 0;
}
inline ::google::protobuf::int32 Edge::edge_id() const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Edge.edge_id)
  return edge_id_;
}
inline void Edge::set_edge_id(::google::protobuf::int32 value) {
  
  edge_id_ = value;
  // @@protoc_insertion_point(field_set:gtpo.pb.Edge.edge_id)
}

// optional int32 src_node_id = 2;
inline void Edge::clear_src_node_id() {
  src_node_id_ = 0;
}
inline ::google::protobuf::int32 Edge::src_node_id() const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Edge.src_node_id)
  return src_node_id_;
}
inline void Edge::set_src_node_id(::google::protobuf::int32 value) {
  
  src_node_id_ = value;
  // @@protoc_insertion_point(field_set:gtpo.pb.Edge.src_node_id)
}

// optional int32 dst_node_id = 3;
inline void Edge::clear_dst_node_id() {
  dst_node_id_ = 0;
}
inline ::google::protobuf::int32 Edge::dst_node_id() const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Edge.dst_node_id)
  return dst_node_id_;
}
inline void Edge::set_dst_node_id(::google::protobuf::int32 value) {
  
  dst_node_id_ = value;
  // @@protoc_insertion_point(field_set:gtpo.pb.Edge.dst_node_id)
}

// optional double weight = 4;
inline void Edge::clear_weight() {
  weight_ = 0;
}
inline double Edge::weight() const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Edge.weight)
  return weight_;
}
inline void Edge::set_weight(double value) {
  
  weight_ = value;
  // @@protoc_insertion_point(field_set:gtpo.pb.Edge.weight)
}

// optional double z = 5;
inline void Edge::clear_z() {
  z_ = 0;
}
inline double Edge::z() const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Edge.z)
  return z_;
}
inline void Edge::set_z(double value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:gtpo.pb.Edge.z)
}

// optional .google.protobuf.Any user1 = 42;
inline bool Edge::has_user1() const {
  return !_is_default_instance_ && user1_ != NULL;
}
inline void Edge::clear_user1() {
  if (GetArenaNoVirtual() == NULL && user1_ != NULL) delete user1_;
  user1_ = NULL;
}
inline const ::google::protobuf::Any& Edge::user1() const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Edge.user1)
  return user1_ != NULL ? *user1_ : *default_instance_->user1_;
}
inline ::google::protobuf::Any* Edge::mutable_user1() {
  
  if (user1_ == NULL) {
    user1_ = new ::google::protobuf::Any;
  }
  // @@protoc_insertion_point(field_mutable:gtpo.pb.Edge.user1)
  return user1_;
}
inline ::google::protobuf::Any* Edge::release_user1() {
  // @@protoc_insertion_point(field_release:gtpo.pb.Edge.user1)
  
  ::google::protobuf::Any* temp = user1_;
  user1_ = NULL;
  return temp;
}
inline void Edge::set_allocated_user1(::google::protobuf::Any* user1) {
  delete user1_;
  user1_ = user1;
  if (user1) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:gtpo.pb.Edge.user1)
}

// -------------------------------------------------------------------

// Group

// optional int32 group_id = 1;
inline void Group::clear_group_id() {
  group_id_ = 0;
}
inline ::google::protobuf::int32 Group::group_id() const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Group.group_id)
  return group_id_;
}
inline void Group::set_group_id(::google::protobuf::int32 value) {
  
  group_id_ = value;
  // @@protoc_insertion_point(field_set:gtpo.pb.Group.group_id)
}

// optional string label = 2;
inline void Group::clear_label() {
  label_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Group::label() const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Group.label)
  return label_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Group::set_label(const ::std::string& value) {
  
  label_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gtpo.pb.Group.label)
}
inline void Group::set_label(const char* value) {
  
  label_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gtpo.pb.Group.label)
}
inline void Group::set_label(const char* value, size_t size) {
  
  label_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gtpo.pb.Group.label)
}
inline ::std::string* Group::mutable_label() {
  
  // @@protoc_insertion_point(field_mutable:gtpo.pb.Group.label)
  return label_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Group::release_label() {
  // @@protoc_insertion_point(field_release:gtpo.pb.Group.label)
  
  return label_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Group::set_allocated_label(::std::string* label) {
  if (label != NULL) {
    
  } else {
    
  }
  label_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), label);
  // @@protoc_insertion_point(field_set_allocated:gtpo.pb.Group.label)
}

// optional double x = 3;
inline void Group::clear_x() {
  x_ = 0;
}
inline double Group::x() const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Group.x)
  return x_;
}
inline void Group::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:gtpo.pb.Group.x)
}

// optional double y = 4;
inline void Group::clear_y() {
  y_ = 0;
}
inline double Group::y() const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Group.y)
  return y_;
}
inline void Group::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:gtpo.pb.Group.y)
}

// optional double z = 5;
inline void Group::clear_z() {
  z_ = 0;
}
inline double Group::z() const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Group.z)
  return z_;
}
inline void Group::set_z(double value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:gtpo.pb.Group.z)
}

// optional double width = 6;
inline void Group::clear_width() {
  width_ = 0;
}
inline double Group::width() const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Group.width)
  return width_;
}
inline void Group::set_width(double value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:gtpo.pb.Group.width)
}

// optional double height = 7;
inline void Group::clear_height() {
  height_ = 0;
}
inline double Group::height() const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Group.height)
  return height_;
}
inline void Group::set_height(double value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:gtpo.pb.Group.height)
}

// repeated int32 node_ids = 12;
inline int Group::node_ids_size() const {
  return node_ids_.size();
}
inline void Group::clear_node_ids() {
  node_ids_.Clear();
}
inline ::google::protobuf::int32 Group::node_ids(int index) const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Group.node_ids)
  return node_ids_.Get(index);
}
inline void Group::set_node_ids(int index, ::google::protobuf::int32 value) {
  node_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:gtpo.pb.Group.node_ids)
}
inline void Group::add_node_ids(::google::protobuf::int32 value) {
  node_ids_.Add(value);
  // @@protoc_insertion_point(field_add:gtpo.pb.Group.node_ids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Group::node_ids() const {
  // @@protoc_insertion_point(field_list:gtpo.pb.Group.node_ids)
  return node_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Group::mutable_node_ids() {
  // @@protoc_insertion_point(field_mutable_list:gtpo.pb.Group.node_ids)
  return &node_ids_;
}

// optional .google.protobuf.Any user1 = 42;
inline bool Group::has_user1() const {
  return !_is_default_instance_ && user1_ != NULL;
}
inline void Group::clear_user1() {
  if (GetArenaNoVirtual() == NULL && user1_ != NULL) delete user1_;
  user1_ = NULL;
}
inline const ::google::protobuf::Any& Group::user1() const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Group.user1)
  return user1_ != NULL ? *user1_ : *default_instance_->user1_;
}
inline ::google::protobuf::Any* Group::mutable_user1() {
  
  if (user1_ == NULL) {
    user1_ = new ::google::protobuf::Any;
  }
  // @@protoc_insertion_point(field_mutable:gtpo.pb.Group.user1)
  return user1_;
}
inline ::google::protobuf::Any* Group::release_user1() {
  // @@protoc_insertion_point(field_release:gtpo.pb.Group.user1)
  
  ::google::protobuf::Any* temp = user1_;
  user1_ = NULL;
  return temp;
}
inline void Group::set_allocated_user1(::google::protobuf::Any* user1) {
  delete user1_;
  user1_ = user1;
  if (user1) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:gtpo.pb.Group.user1)
}

// -------------------------------------------------------------------

// Void

// -------------------------------------------------------------------

// Graph

// optional int32 node_count = 1;
inline void Graph::clear_node_count() {
  node_count_ = 0;
}
inline ::google::protobuf::int32 Graph::node_count() const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Graph.node_count)
  return node_count_;
}
inline void Graph::set_node_count(::google::protobuf::int32 value) {
  
  node_count_ = value;
  // @@protoc_insertion_point(field_set:gtpo.pb.Graph.node_count)
}

// optional int32 edge_count = 2;
inline void Graph::clear_edge_count() {
  edge_count_ = 0;
}
inline ::google::protobuf::int32 Graph::edge_count() const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Graph.edge_count)
  return edge_count_;
}
inline void Graph::set_edge_count(::google::protobuf::int32 value) {
  
  edge_count_ = value;
  // @@protoc_insertion_point(field_set:gtpo.pb.Graph.edge_count)
}

// optional int32 group_count = 3;
inline void Graph::clear_group_count() {
  group_count_ = 0;
}
inline ::google::protobuf::int32 Graph::group_count() const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Graph.group_count)
  return group_count_;
}
inline void Graph::set_group_count(::google::protobuf::int32 value) {
  
  group_count_ = value;
  // @@protoc_insertion_point(field_set:gtpo.pb.Graph.group_count)
}

// repeated .google.protobuf.Any nodes = 12;
inline int Graph::nodes_size() const {
  return nodes_.size();
}
inline void Graph::clear_nodes() {
  nodes_.Clear();
}
inline const ::google::protobuf::Any& Graph::nodes(int index) const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Graph.nodes)
  return nodes_.Get(index);
}
inline ::google::protobuf::Any* Graph::mutable_nodes(int index) {
  // @@protoc_insertion_point(field_mutable:gtpo.pb.Graph.nodes)
  return nodes_.Mutable(index);
}
inline ::google::protobuf::Any* Graph::add_nodes() {
  // @@protoc_insertion_point(field_add:gtpo.pb.Graph.nodes)
  return nodes_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any >*
Graph::mutable_nodes() {
  // @@protoc_insertion_point(field_mutable_list:gtpo.pb.Graph.nodes)
  return &nodes_;
}
inline const ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any >&
Graph::nodes() const {
  // @@protoc_insertion_point(field_list:gtpo.pb.Graph.nodes)
  return nodes_;
}

// repeated .google.protobuf.Any edges = 13;
inline int Graph::edges_size() const {
  return edges_.size();
}
inline void Graph::clear_edges() {
  edges_.Clear();
}
inline const ::google::protobuf::Any& Graph::edges(int index) const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Graph.edges)
  return edges_.Get(index);
}
inline ::google::protobuf::Any* Graph::mutable_edges(int index) {
  // @@protoc_insertion_point(field_mutable:gtpo.pb.Graph.edges)
  return edges_.Mutable(index);
}
inline ::google::protobuf::Any* Graph::add_edges() {
  // @@protoc_insertion_point(field_add:gtpo.pb.Graph.edges)
  return edges_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any >*
Graph::mutable_edges() {
  // @@protoc_insertion_point(field_mutable_list:gtpo.pb.Graph.edges)
  return &edges_;
}
inline const ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any >&
Graph::edges() const {
  // @@protoc_insertion_point(field_list:gtpo.pb.Graph.edges)
  return edges_;
}

// repeated .google.protobuf.Any groups = 14;
inline int Graph::groups_size() const {
  return groups_.size();
}
inline void Graph::clear_groups() {
  groups_.Clear();
}
inline const ::google::protobuf::Any& Graph::groups(int index) const {
  // @@protoc_insertion_point(field_get:gtpo.pb.Graph.groups)
  return groups_.Get(index);
}
inline ::google::protobuf::Any* Graph::mutable_groups(int index) {
  // @@protoc_insertion_point(field_mutable:gtpo.pb.Graph.groups)
  return groups_.Mutable(index);
}
inline ::google::protobuf::Any* Graph::add_groups() {
  // @@protoc_insertion_point(field_add:gtpo.pb.Graph.groups)
  return groups_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any >*
Graph::mutable_groups() {
  // @@protoc_insertion_point(field_mutable_list:gtpo.pb.Graph.groups)
  return &groups_;
}
inline const ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any >&
Graph::groups() const {
  // @@protoc_insertion_point(field_list:gtpo.pb.Graph.groups)
  return groups_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace gtpo

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_gtpo_2eproto__INCLUDED
